/**
 * Canonical InterviewKit TypeScript contract.
 *
 * These types are the single source of truth for the shape of a generated
 * interview preparation kit. The Zod schemas in ../schemas/interview-kit.ts
 * mirror this contract exactly and are the runtime enforcement of it.
 *
 * Do not define competing copies of these types anywhere else in the repo.
 */

/** Provenance of the data used to build a kit. */
export interface InterviewKitSource {
  company: string;
  company_url: string;
  jd_chars: number;
  researched_at: string;
}

/** Short factual brief about the hiring company. */
export interface CompanyBrief {
  summary: string;
  products: string[];
  tech_signals: string[];
  notes: string[];
}

export type RequirementKind = 'technical' | 'behavioural' | 'domain';
export type RequirementPriority = 'must' | 'nice';

/**
 * A single requirement extracted from the job description.
 * `id` is generated by the application (never trusted from an LLM).
 */
export interface Requirement {
  id: string;
  text: string;
  kind: RequirementKind;
  priority: RequirementPriority;
}

/** The role being prepared for, plus its extracted requirements. */
export interface InterviewRole {
  title: string;
  seniority: string;
  requirements: Requirement[];
}

export type QuestionCategory =
  | 'technical'
  | 'behavioural'
  | 'system-design'
  | 'company-fit';

/** 1 = easiest, 3 = hardest. */
export type QuestionDifficulty = 1 | 2 | 3;

export interface InterviewQuestion {
  id: string;
  prompt: string;
  category: QuestionCategory;
  difficulty: QuestionDifficulty;
  requirement_ids: string[];
  answer_outline: string;
}

export interface InterviewFlashcard {
  id: string;
  front: string;
  back: string;
  requirement_ids: string[];
}

export interface InterviewScheduleDay {
  day: number;
  minutes: number;
  question_ids: string[];
  focus: string;
}

export interface InterviewSchedule {
  days_available: number;
  days: InterviewScheduleDay[];
}

export interface InterviewCoverage {
  passes: number;
  uncovered_requirement_ids: string[];
  notes: string[];
}

export interface InterviewKit {
  source: InterviewKitSource;
  company: CompanyBrief;
  role: InterviewRole;
  questions: InterviewQuestion[];
  flashcards: InterviewFlashcard[];
  schedule: InterviewSchedule;
  coverage: InterviewCoverage;
}
